### ISSUE TITLE
node.js Memory leak

### ISSUE THREAD

**Issue by lukavom** [AlbertoPdRF/root-file-viewer#15]
Hello Alberto,
the plugin has been very convenient for me, so thank you for providing it!
Unfortunately it has caused some issues in my group. Whenever I try to view a large root file, a node.js process is started that completely eats up RAM and swap on our machines, causing large problems. The issue is reproducible by simply trying to view a file of about 20Gb. A few months ago viewing the same file worked without issue.
Do you have any Idea what can cause this? Any help is appreciated.
Best regards,
Luka

**Comment by AlbertoPdRF** [comment]
Hi @lukavom!

I can indeed reproduce the issue. I'm adding @linev to the conversation because `JSROOT` is doing all the work here. Maybe this is related to #10?

**Comment by linev** [comment]
Access to large ROOT files should be solved with https://github.com/AlbertoPdRF/root-file-viewer/pull/20

**Comment by linev** [comment]
@Ilya0527 

Since a long time JSROOT provides `FileProxy` API to read ROOT files from arbitrary source.
And there is PR #20 which solves problem with large files in `root-file-viewer`.
I really surprised that it is not applied yet.

@AlbertoPdRF - please check PR. 
The only change which is probably needed - adjust JSROOT version in the PR.

**Comment by AlbertoPdRF** [comment]
Hi,

The problem is still that VSCode doesn't allow to read in chunks, see: https://github.com/microsoft/vscode/issues/84515#issuecomment-1205111291

**Comment by linev** [comment]
Hi Alberto,

So one need to use internal http protocol of VSCode. 

Maybe one have to prevent JSROOT issuing multi-range requests?
Did you set `settings.MaxRanges = 1;`  for JSROOT?

**Comment by linev** [comment]
PR #20 was attempt to fully avoid http protocol on the place where it does not needed.
If one have to keep usage of `http` protocol - one should understand why it makes problem.
JSROOT never tries to load full file content - but sometime http servers response on multi-range requests in such wrong way.
Therefore disable multi-range requests may help.

**Comment by linev** [comment]
> Which servers have you actually seen do this in the wild?

It is `https://root.cern/files/` server; some version of Apache.
It does not like when ranges requested not in sorted order - and sometime starts sending complete file content back.

`MaxRanges = 1` is fallback solution  - if JSROOT detects such situation.
For `vscode` plugin such setting should be ok - while here expected network delay is minimal.
